apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bundler
  namespace: graph
spec:
  encryptedData:
    bearer-token: AgC5sw7J7xp39lnBhhJZ+hmWiPrAmCqoLt8SNxmWlM+CzxJSi4p1mdnNmbedpI13u9YztPpohW7g3JrnVzB4VXVndtsAX0Qg/rLh5ZmQz0uXUaGxyyTVSdLPXXONjJEKooRkXXkVRmo7mDKiXIsR6m28j5i6Xj57hR7cCKfdT25nbWBGkdPDTJBCbaUeHewTcNDLtCZu+T/ShXvExC9MVNTci6NfKzPs83AENtTJIkL836N+ATzlZIRN7a2lXfCjgJqENI0kn55W2Xq2+YuCJwJq2tFy7H4H57to4jRv4k+iqm4B5XJk6LnxAZAABud5nYU9jrVBCJ25V3jHx9z9g4DN0/1znQaTeYIHIPPkZPFSAUSQ9j9QoJ3Y1epy6n7ixyY1LTxe2AbsMj31ZEivafPcNRx8kyOyyuFInzPAS7tPPX8PRz9EZifs6K49szU1Cn/5uGWbEXZFaGxr7v6soxYBcZuTH9FAk4jPwr3c76QnPGJouO3tHLS1iZrsPqdzLWmeAT3m4trPysPveN8vou567t7lVtvnty/dIntCKsLxDo1nywigFAI9mnpCrbLzJBs0reNafEX/WKybFiuFvdmDDykwlLhB6i63virqpc0BxaVtX2EMoeq4JNDupuqGj9QKL4tgGUjdKP4zMS5EpZZm1Ft681q6y71qHI3ectzeXiK44WH9Lxhw+8T84x42bNsNfsAMfBLzbVaKyvcwCcriNV5OpFFGb8mWkjX0p7l0H75Squ4=
  template:
    metadata:
      creationTimestamp: null
      name: bundler
      namespace: graph

