name: Helm Charts

on:
  push:
  pull_request:

jobs:
  lint:
    # Deduplicate jobs from pull requests and branch pushes within the same repo.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0

      - name: Setup Helm
        uses: azure/setup-helm@v3.5

      - name: Setup chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Lint
        run: >
          ct
          lint
          --target-branch=${{ github.event.repository.default_branch }}
          --validate-maintainers=false

  build_publish:
    needs:
      - lint
    # Deduplicate jobs from pull requests and branch pushes within the same repo.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.4

      - name: Retrieve chart dependencies
        working-directory: charts/sessions
        run: helm dependency update

      - name: Package chart
        working-directory: charts/sessions
        run: helm package .

      - name: Generate Image Name
        run: echo IMAGE_REPOSITORY=oci://ghcr.io/$(echo "${{ github.repository }}-chart" | tr '[:upper:]' '[:lower:]' | tr '[_]' '[\-]') >> $GITHUB_ENV

      - name: Log in to GitHub Docker Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish chart
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        working-directory: charts/sessions
        run: helm push $(ls sessions-*.tgz) ${{ env.IMAGE_REPOSITORY }}
